Generic File Upload
instantshare/instantshare pull request #44
Opened 2017-04-11 20:18 UTC by dtext

Allows users to upload and share files present on the local file system.

### Commit Summary
The first commit moves a lot of code from the specific subcommands to the `storage` package. The reasoning behind this is explained in the commit message below.

The second commit just adds the few lines of code that were then needed to implement sharing of existing files.

### Relevant issues
Closes #2

2017-04-13 13:25 UTC, denniseffing requested changes
Solid implementation, even though I dislike the new multi-purpose of our storage module (but it is better than before). I don't have a better solution though, so this has to do for now.

2017-04-13 13:25 UTC, denniseffing commented on src/cli/file.py
> +        storage.upload_to(hoster, file)
What happens here if the user enters an invalid combination of hoster and file?

2017-04-13 13:25 UTC, denniseffing commented on src/tools/toolbox.py
> +    return "{}/instantshare_{}_{}.png".format(gettempdir(), media_type, strftime("%Y-%m-%d_%H-%I-%S"))
Calling `build_filename` with `media_type=text` results in a file named `<tempdir>/instantshare_<media_type>_<timestamp>.PNG` which only makes sense for screenshots.

2017-04-13 15:42 UTC, dtext commented on src/cli/file.py
> +        storage.upload_to(hoster, file)
Any checks of that kind would need to be done inside the different storage modules. We don't really have proper error handling for that yet.

2017-04-13 15:43 UTC, dtext commented on src/tools/toolbox.py
> +    return "{}/instantshare_{}_{}.png".format(gettempdir(), media_type, strftime("%Y-%m-%d_%H-%I-%S"))
That's right. I will see what I can come up with.

2017-04-16 19:09 UTC, dtext commented
@denniseffing What do you think about this? We know the file name and extension for every file that is created by us (screenshots, recordings, etc.). For existing files being shared (which could have any file extension), we don't even need to set a filename anyway.

2017-04-19 16:54 UTC, denniseffing approved these changes

2017-04-19 17:14 UTC, merged