Standardize the storage providers
instantshare/instantshare pull request #45
Opened 2017-04-15 15:28 UTC by florianluediger

I mostly standardized the storage providers to use the KVStore for encrypted storage where possible and our OAuth implicit flow implementation for authentication with Google Drive.
I am currently using the app key related to my private Google account for Google Drive, we should update this to the organizations account app key before merging.

ToDo:

- [ ] update app key of Google Drive in the configuration

2017-04-15 20:54 UTC, dtext requested changes
The changes to the google driver storage provider and the default config seem fine to me, but the sftp module needs a bit more work, I think. I see how treating them alike makes it easier, but a user password is not the same as a key passphrase, and *both* could be required for authentication.

2017-04-16 14:44 UTC, florianluediger commented
Up to this point, there was no option to use a key passphrase in combination with a password, so I did not remove any functionality with my changes. However, I see your point and I will give this some work to implement the option for authentication with a key passphrase and a password.

2017-04-17 10:12 UTC, dtext commented
That would be great 👍

2017-04-18 17:35 UTC, dtext commented
To be clear: You don't need to implement new functionality in this PR, but it would be beneficial to treat the passphrase and password as different variables, so we can easily work off of that in the future.

2017-04-18 19:31 UTC, dtext approved these changes

2017-04-19 10:45 UTC, dtext approved these changes
I don't really get the commit message, but apart from that, everything seems to be covered now. @denniseffing If you want, you can have a second look, but it looks fine now from my perspective.

2017-04-19 14:34 UTC, merged